### ISSUE TITLE
Stuck at "writing updated etag for model info"

### ISSUE THREAD

**Issue by yaoberh** [rteabeault/AnkiSpacy#10]
Something seems to be stuck, and the process manager shows 0% cpu utilization for anki.
Running x64 manjaro.
Also getting this error when launching anki:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.9.2 Qt 5.15.2 PyQt 5.15.4
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2021-03-20 13:10:48
Add-ons possibly involved: ⁨AnkiSpacy-master⁩

Caught exception:
Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/AnkiSpacy-master/__init__.py", line 65, in <lambda>
    spacy_info_loader.loaded.connect(lambda spacy_info: _on_spacy_info_loaded(spacy_info, dialog))
  File "/home/yaoberh/.local/share/Anki2/addons21/AnkiSpacy-master/__init__.py", line 86, in _on_spacy_info_loaded
    dialog.set_spacy_info(spacy_info)
  File "/home/yaoberh/.local/share/Anki2/addons21/AnkiSpacy-master/ui/spacy_dialog.py", line 147, in set_spacy_info
    self.model = SpacyItemListModel(self.spacy_info)
  File "/home/yaoberh/.local/share/Anki2/addons21/AnkiSpacy-master/ui/spacy_model.py", line 18, in __init__
    self.rebuild_model()
  File "/home/yaoberh/.local/share/Anki2/addons21/AnkiSpacy-master/ui/spacy_model.py", line 24, in rebuild_model
    spacy_models = create_model_packages(self.spacy_info)
  File "/home/yaoberh/.local/share/Anki2/addons21/AnkiSpacy-master/spacy_packages.py", line 137, in create_model_packages
    return _create_model_packages(spacy_info, model_names, installed_models)
  File "/home/yaoberh/.local/share/Anki2/addons21/AnkiSpacy-master/spacy_packages.py", line 161, in _create_model_packages
    details=spacy_info.load_model_info(model_name, versions[0]),
  File "/home/yaoberh/.local/share/Anki2/addons21/AnkiSpacy-master/spacy_info.py", line 276, in load_model_info
    with open(model_info_path(name, version)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yaoberh/.local/share/Anki2/addons21/AnkiSpacy-master/user_files/_cache/spacy/models/en_vectors_web_lg-3.0.0.json'

**Comment by yaoberh** [comment]
Fixes by manually adding the file from spacy models and putting it into the folder.
