### ISSUE TITLE
Japanese not working

### ISSUE THREAD

**Issue by thinkingbox12** [rteabeault/AnkiSpacy#7]
See this reply: https://github.com/kaegi/MorphMan/pull/221#issuecomment-754379723

**Comment by rteabeault** [comment]
Thanks so much for taking a look at this @thinkingbox12. I am currently trying to reproduce but it seems that on the latest version of Windows there is an issue with one of Spacy's dependencies `numpy` that I need to work past. 

```
The current Numpy installation fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
``` 

This appears to be an issue that is in the pipeline of being fixed by Microsoft. If I can work around it I will try to reproduce your issue. At first glance the error you are getting appears to be something missing on your Windows machine that is needed by sudachi

```
ImportError: DLL load failed while importing _dartsclone: The specified module could not be found.
```

I will report back as soon as I figure something out.

**Comment by thinkingbox12** [comment]
Had a little bit of time to get you the error I was having on Ubuntu when trying to install Japanese dictionary.

**Comment by rteabeault** [comment]
Oh that looks fun. So gcc is failing to compile sudachi on linux. Both of these issues seem to be not necessarily problems with this Anki addon but with OS related issues. It would be good to figure out how to workaround them though and document.

**Comment by thinkingbox12** [comment]
I'd love to help. Where do I begin?
Can also test on a Mac tomorrow.

**Comment by rteabeault** [comment]
Ok. I have seen three problems so far and here are the workarounds

1. Windows only: There is an issue with spacy's dependency `numpy` and windows. After installing a spacy model on windows (if you have the windows October Update `2004`) you may see 

    ```
    The current Numpy installation ('<some_path_to_numpy_init_file>') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
    ```
    To fix  this open `some_path_to_numpy_init_file` seen in the error. Replace the line 

    ```python
    if sys.platform == "win32" and sys.maxsize > 2**32:
      _win_os_check()
    ```

    with 

    ```python
    if sys.platform == "win32" and sys.maxsize > 2**32:
       #  _win_os_check()
      pass
    ```

    Once https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html is resolved this step should be unnecessary. 

2. Windows Only: You may see the error 
    ```
    ImportError: Japanese support requires SudachiPy and SudachiDict-core (https://github.com/WorksApplications/SudachiPy). Install with `pip install sudachipy sudachidict_core` or install spaCy with `pip install spacy[ja]`.
    ```

    And further up in the error message you see 

    ```
    ImportError: DLL load failed while importing _dartsclone: The specified module could not be found.
    ```

    This can be fixed by installing the visual c++ redistributable. 
    1. Go to https://visualstudio.microsoft.com/downloads/ 
    2. At the bottom select ![image](https://user-images.githubusercontent.com/65126/103619450-01d7c400-4eef-11eb-824e-23bae243d41e.png)
    3. Download and install ![image](https://user-images.githubusercontent.com/65126/103619590-406d7e80-4eef-11eb-95d9-6df162892a25.png) for your system

3. Windows only: When running Morphman recalc you see the following error

    ```
    OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\workspace\\AnkiSpacy\\src\\user_files\\packages\\sudachidict_core' -> 'C:\\workspace\\AnkiSpacy\\src\\user_files\\packages\\sudachidict'
    ```

    Further up in the error you will also see 

    ```
      File "C:\workspace\AnkiSpacy\src\user_files\packages\sudachipy\config.py", line 56, in create_default_link_for_sudachidict_core
    dict_path = Path(import_module('sudachidict').__file__).parent
    File "importlib\__init__.py", line 127, in import_module
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'sudachidict'
    ```

    This seems to be sudachi trying to create a symlink to the installed sudachidict (in this case, by default it is sudachidict_core). I thought restarting Anki running as administrator would fix the problem but Morphman then disappeared from my Anki tools. I will try to figure that out tomorrow. In the meantime you can create a symlink by 
    1. Start a command prompt as administrator.
    2. Create a symlink from sudachidict to sudachidict_core
    ```
    mklink /D <anki_spacy_addon_path>packages\sudachidict <anki_spacy_addon_path>\packages\sudachidict_core
    ````
    
Tomorrow I will look into the linux compiler issue.

**Comment by rteabeault** [comment]
> Can also test on a Mac tomorrow.

**Comment by rteabeault** [comment]
Did not mean to close this. Reopen.

**Comment by thinkingbox12** [comment]
Japanese small model (windows) worked after these fixes (install and recalc). Went to install medium model right after. Got this exception
```
Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Anki2\addons21\src\_vendor\pip\_internal\cli\base_command.py", line 224, in _main
    status = self.run(options, args)
  File "C:\Users\AppData\Roaming\Anki2\addons21\src\_vendor\pip\_internal\cli\req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "C:\Users\AppData\Roaming\Anki2\addons21\src\_vendor\pip\_internal\commands\install.py", line 452, in run
    self._handle_target_dir(
  File "C:\Users\AppData\Roaming\Anki2\addons21\src\_vendor\pip\_internal\commands\install.py", line 505, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "shutil.py", line 730, in rmtree
  File "shutil.py", line 608, in _rmtree_unsafe
  File "shutil.py", line 606, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\AppData\\Roaming\\Anki2\\addons21\\src\\user_files\\packages\\dartsclone\\_dartsclone.cp38-win_amd64.pyd'[0m
```
I noticed it reinstalls all the packages for each model (cython, sortedcontainers, dartsclone, sudachipy). Just something to note

**Comment by rteabeault** [comment]
> I noticed it reinstalls all the packages for each model (cython, sortedcontainers, dartsclone, sudachipy). Just something to note

This is known. The code to install via pip uses the `-t` and `--upgrade` options. In this case it always tries to install the packages even if they are already there. It is unfortunate but I could not find a better way to do it.

> KeyError: "[E002] Can't find factory for 'parser'. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories['parser']` or remove it from the model meta and add it via `nlp.add_pipe` instead."

I am not sure what is happening here. I will try to reproduce this.

**Comment by rteabeault** [comment]
> PermissionError: [WinError 5] Access is denied: 'C:\Users\AppData\Roaming\Anki2\addons21\src\user_files\packages\dartsclone\_dartsclone.cp38-win_amd64.pyd'

I have reproduced this. If you install ja_core_news_md and recalc and then try to install any other model that has a dependency on dartsclone you will see this error. I believe it is because the file listed in the error is still being held open by the anki process. If you restart anki and try to install it again you won't see this error. I believe though that even when you see the error the model has properly been installed. You just need to restart. This is a byproduct of what you astutely observed that dependencies are reinstalled for each model. It is unfortunate. I will try to think of a fix but at this point I am not sure how to resolve this without restarting anki.

**Comment by rteabeault** [comment]
I continue to run into problems. All around Chinese and Japanese and most in Windows. For example, it becomes impossible to remove some models or spacy if Morphman has already loaded the packages. This is because Windows will not allow you to delete files in use and anki has already loaded some DLLs from the packages. My intent all along was to create an easy to use package manager that did not require the user to install python. But trying to install packages and load them while anki is already running is turning out to be a large pain. I am partially considering ditching the GUI package manager and instead just giving users instructions on how to install packages via pip.

**Comment by thinkingbox12** [comment]
I don't think it would be all that bad. I would imagine the users that would benefit from the more precise Japanese parsing wouldn't mind running cmd.

I'd like to start investigating the other issue I posted. I am a beginner to troubleshooting/testing, what exactly does setting up a dev environment consist of and how is it different from just running Anki as a normal user?

**Comment by rteabeault** [comment]
The simplest thing to do is to take the `src` directory of the addon and place it in your anki's `addons21` directory. You can call it whatever. You can then just modify the code and run anki as normal to test. Alternatively you can symlink from your addons21 directory to wherever the source is.

**Comment by thinkingbox12** [comment]
Okay. I think I've centered in on a problem I was having. For whatever reason, when using any Spacy-based morphemizer when recalculating cards (after generating a frequency list from a study plan in the Readability Analyzer), it is not reading from the frequency.txt file, and therefore no cards are tagged with the 'mm_FrequencyList' tag. It seems that this error occurs regardless of the morphemizer that I use, as it fails with both MeCab and Spacy. Moreover, Mecab has no trouble reading from a frequency.txt generated by Spacy.
So I've no idea for what reason this is occurring, because if Spacy was broken it wouldn't recalc properly at all, it just seems there's a bug with reading frequency.txt and tagging cards/ reordering their priority as such.
What do you think?

**Comment by thinkingbox12** [comment]
Ok. It seems the problem is, when using Spacy, the master_freq counter in frequency.txt is not updating. Still unsure as to why.

**Comment by thinkingbox12** [comment]
Update #2. The new models (seem?) to be working when the frequency.txt is generated with the readability tool WITH THE MODEL that you want to read it with. This means previously generated frequency lists (typically made with MeCab) are incompatible. I'm not sure why this is. Probably something to do with how spacy lists results/classifies parses, but I haven't figured it out further.

Despite this, morphman does not tag whether a card is on your frequency list or not.

Additionally, it feels that the cards aren't adhering to the study plan as well as I might have remembered (this might totally be me though, I wasn't particularly familiar with the scoring algorithm before I looked at the code, so maybe it's working the same way as before).
